# todo > docker 내부에서 cfg 파일 분리해야함 to run in docker 주석 삭제필요
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ACB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    # to run in docker
#    url: jdbc:mysql://docker.for.mac.localhost:3306/ACB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    check-template-location: true
  cache:
    type: redis
  redis:
    cache:
      value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
  main:
    allow-bean-definition-overriding: true


server:
  port: 10001
  servlet:
    context-path: /acb
  shutdown: graceful
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.data.elasticsearch.client.WIRE: trace
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql:
            BasicBinder: trace

#springdoc >> 미사용
#springdoc:
##  api-docs:
##    enabled: false
#  packagesToScan: com.kyu9.accountbook.swagger
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-request-duration: true
#    operations-sorter: alpha

springfox:
  documentation:
    swagger:
      v3:
        api-docs:
          enabled: true


elasticsearch.url: localhost
#to run in docker
#elasticsearch.url: docker.for.mac.localhost
elasticsearch.port: 9200
