spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ACB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    check-template-location: true
  cache:
    type: redis
  redis:
    cache:
      value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer


server:
  port: 10001
  shutdown: graceful
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
    org:
      springframework:
        web : info
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace


springdoc:
#  packages-to-scan: com.kyu9.accountbook.swagger
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    #path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true