spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ACB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    check-template-location: true
  cache:
    type: redis
  redis:
    cache:
      value-serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer


server:
  port: 10001
  shutdown: graceful
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
    org:
      springframework:
        web : info
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace


springdoc:
  api-docs:
    enabled: false

