spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KAB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



server:
  port: 10001
  shutdown: graceful
  devtools:
    restart:
      enabled: true



springdoc:
  api-docs:
    path: /docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
  cache:
    disabled: true