openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Account Book'
  description: 'account book api document'
servers:
  - url: http://localhost:8080
tags:
  - name: "Util"
    description: "Utility API"

paths:
  /sample/jsonify:
    get:
      tags:
        - "Util"
      summary: "Lombok @toString to json format"
      description: "Lombok @toString to json format"
      operationId: toStringToJSON
      responses:
        200:
          description: "Success"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string